export const TRAER_PUBLICACIONES = 'TRAER_PUBLICACIONES';
export const CARGANDO_PUBLICACIONES = 'CARGANDO_PUBLICACIONES';
export const ERROR_PUBLICACIONES = 'ERROR_PUBLICACIONES';
export const ACTUALIZAR = 'PUBLICACIONES_ACTUALIZAR';
export const COMENTARIOS_CARGANDO = 'COMENTARIOS_CARGANDO';
export const COMENTARIOS_ERROR = 'COMENTARIOS_ERROR';
export const COMENTARIOS_ACTUALIZAR = 'COMENTARIOS_ACTUALIZAR';
