export const TRAER_PUBLICACIONES = 'TRAER_PUBLICACIONES';
export const CARGANDO_PUBLICACIONES = 'CARGANDO_PUBLICACIONES';
export const ERROR_PUBLICACIONES = 'ERROR_PUBLICACIONES';
export const PUBLICACIONES_TRAER_POR_USUARIO = 'PUBLICACIONES_TRAER_POR_USUARIO';